
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Sep 15 00:05:28 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 23;
  public static final int LBRACKET = 10;
  public static final int CHAR = 49;
  public static final int CONST = 3;
  public static final int GRT = 24;
  public static final int NOTEQUAL = 34;
  public static final int LPAREN = 7;
  public static final int SEMI = 6;
  public static final int CONTINUE = 28;
  public static final int DECR = 39;
  public static final int INCR = 40;
  public static final int MINUS = 14;
  public static final int RPAREN = 8;
  public static final int IS = 11;
  public static final int AND = 31;
  public static final int LT = 22;
  public static final int OR = 32;
  public static final int BOOL = 48;
  public static final int COMMA = 15;
  public static final int DIV = 37;
  public static final int PLUS = 13;
  public static final int IF = 26;
  public static final int DOT = 18;
  public static final int FINDANY = 41;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 35;
  public static final int RBRACKET = 9;
  public static final int GRTE = 25;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int MUL = 38;
  public static final int PERCENT = 21;
  public static final int NUMBER = 46;
  public static final int IDENT = 47;
  public static final int BREAK = 30;
  public static final int VOID = 17;
  public static final int ARROW = 20;
  public static final int FOREACH = 29;
  public static final int BIN = 45;
  public static final int LBRACE = 4;
  public static final int ELSE = 27;
  public static final int READ = 36;
  public static final int WHILE = 33;
  public static final int RBRACE = 5;
  public static final int PROG = 2;
  public static final int COUNT = 43;
  public static final int MAX = 44;
  public static final int PRINT = 16;
  public static final int FINDANDREPLACE = 42;
}

